AWSTemplateFormatVersion: '2010-09-09'
Description: Highly available 3 Tier architecture for web application

#←←←←←←←←←←←←←← Resources →→→→→→→→→→→→→→#
Resources:

#------------------------- Database Tier RDS Instance -------------------------#
  RDSDBInstance:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: mydatabase
      AllocatedStorage: 20
      DBInstanceClass: db.t3.micro
      Engine: MySQL
      EngineVersion: '8.0'
      MasterUsername: admin
      MasterUserPassword: Aa12345678
      MultiAZ: true # Enable Multi-AZ
      DBSubnetGroupName: !Ref RDSSubnetGroup
      VPCSecurityGroups:
        - !ImportValue DatabaseTierSecurityGroup
  
  RDSSubnetGroup:
    Type: AWS::RDS::DBSubnetGroup
    Properties:
      DBSubnetGroupDescription: Subnet group for RDS
      DBSubnetGroupName: !ImportValue DatabaseTierSecurityGroup
      SubnetIds:
        - !ImportValue DatabaseTierPrivateSubnet1
        - !ImportValue DatabaseTierPrivateSubnet2
